// ---- Alpha 0.4: match systems layered onto the approved Alpha 0.3 battlefield ----
const A04_BLUE='blue',A04_RED='red';
const a04Start=now();
let a04Wave=0,a04NextWave=.5,a04Ended=false,a04PitSpawned=false,a04PitRespawn=0;
const a04PitBuff={blue:0,red:0};
player.gold=500;
const a04Hud={timer:document.querySelector('#matchTimer'),gold:document.querySelector('#goldText'),wave:document.querySelector('#waveText'),pit:document.querySelector('#pitlordText')};
const a04Time=t=>t-a04Start;

function a04Stage(label){return label.includes('T1')?0:label.includes('T2')?1:label.includes('G1')?2:3}
for(const tw of towers){tw.userData.kind='tower';tw.userData.name=`${tw.userData.team.toUpperCase()} ${tw.userData.label}`;tw.userData.stage=a04Stage(tw.userData.label);tw.userData.lane=tw.userData.label[0];tw.userData.alive=true;tw.userData._group=tw;tw.userData.maxHp=[6000,7500,9500,11000][tw.userData.stage];tw.userData.hp=tw.userData.maxHp;tw.userData.damage=[240,290,350,420][tw.userData.stage];tw.userData.range=8.8;}
for(const core of [blueCore,redCore]){core.userData.kind='core';core.userData.name=`${core.userData.team.toUpperCase()} CORE`;core.userData.alive=true;core.userData._group=core;core.userData.hp=18000;core.userData.maxHp=18000;}

const a04Minions=[];
function a04MinionModel(team,type){
  const g=new THREE.Group(),teamMat=new THREE.MeshStandardMaterial({color:team===A04_BLUE?0x4b86c7:0xc45161,emissive:team===A04_BLUE?0x132d50:0x4b101b,emissiveIntensity:.75,roughness:.55});
  const body=new THREE.Mesh(new THREE.CylinderGeometry(.38,.48,.9,7),teamMat);body.position.y=.55;body.castShadow=true;g.add(body);
  const head=new THREE.Mesh(new THREE.SphereGeometry(.32,8,6),materials.steel);head.position.y=1.18;head.castShadow=true;g.add(head);
  if(type==='ranged'){const orb=new THREE.Mesh(new THREE.OctahedronGeometry(.2),team===A04_BLUE?materials.blueGlow:materials.redGlow);orb.position.set(.42,.9,0);g.add(orb)}
  else {const sword=new THREE.Mesh(new THREE.BoxGeometry(.08,1.05,.1),materials.steel);sword.position.set(.46,.8,0);sword.rotation.z=.35;g.add(sword)}
  if(type==='special'){const crown=new THREE.Mesh(new THREE.TorusGeometry(.34,.06,5,12),team===A04_BLUE?materials.blueGlow:materials.redGlow);crown.position.y=1.55;crown.rotation.x=Math.PI/2;g.add(crown)}
  scene.add(g);return {g,body};
}
function a04SpawnMinion(team,lane,type,offset){
  const base=lane==='A'?laneA:laneB, path=(team===A04_BLUE?base:[...base].reverse()).map(p=>new THREE.Vector3(p[0],0,p[1]));
  const model=a04MinionModel(team,type),hp=type==='special'?820:type==='ranged'?560:700;
  model.g.position.copy(path[0]).add(new THREE.Vector3(offset,0,offset));
  const m={kind:'minion',name:`${team.toUpperCase()} ${type.toUpperCase()} MINION`,team,lane,type,group:model.g,body:model.body,hp,maxHp:hp,damage:type==='ranged'?62:72,range:type==='ranged'?5.2:1.55,speed:type==='special'?2.2:2.45,path,index:1,alive:true,nextHit:0,respawnAt:Infinity};a04Minions.push(m);return m;
}
function a04SpawnWave(){a04Wave++;for(const lane of ['A','B'])for(const team of [A04_BLUE,A04_RED]){a04SpawnMinion(team,lane,'melee',-.45);a04SpawnMinion(team,lane,'melee',.45);a04SpawnMinion(team,lane,'ranged',0);a04SpawnMinion(team,lane,'special',team===A04_BLUE?.75:-.75)}announce(`WAVE ${a04Wave} · THE LEGIONS MARCH`,850);}

const a04Jungle=[];
function a04JungleModel(type){
  const g=new THREE.Group(),mat=type==='purple'?materials.purpleGlow:type==='blue'?materials.blueGlow:type==='red'?materials.redGlow:materials.yellowGlow;
  const body=new THREE.Mesh(new THREE.IcosahedronGeometry(type==='purple'?1.35:1.05,1),new THREE.MeshStandardMaterial({color:type==='purple'?0x55405e:0x514a43,roughness:.72,metalness:.12}));body.position.y=1.15;body.scale.set(1.15,.9,1.25);body.castShadow=true;g.add(body);
  for(let i=0;i<4;i++){const s=new THREE.Mesh(new THREE.ConeGeometry(.14,.72,5),mat);s.position.set((i-1.5)*.32,2.15,.08);s.rotation.z=(i-1.5)*.14;g.add(s)}scene.add(g);return {g,body};
}
for(let i=0;i<camps.length;i++){const [x,z,type]=camps[i],m=a04JungleModel(type);m.g.position.set(x,0,z);const hp=type==='purple'?3000:2100;a04Jungle.push({kind:'jungle',name:type==='purple'?'RIFT BRUTE':type==='blue'?'AZURE WARDEN':type==='red'?'CRIMSON MAULER':'STONEBACK',team:'neutral',type,group:m.g,body:m.body,hp,maxHp:hp,damage:type==='purple'?150:105,alive:true,spawn:new THREE.Vector3(x,0,z),respawnAt:Infinity,nextHit:0,speed:1.6});}

pitlord.visible=false;
const a04Pit={kind:'pitlord',name:'PITLORD',team:'neutral',group:pitlord,body:pitlord.userData.body,hp:9000,maxHp:9000,damage:230,alive:false,nextHit:0,lastTeam:null};
function a04SpawnPit(force=false){if(a04Pit.alive)return;const mt=a04Time(now());if(!force&&mt<210)return;a04Pit.alive=true;a04Pit.hp=a04Pit.maxHp;a04Pit.group.visible=true;a04Pit.group.position.set(0,0,0);a04PitSpawned=true;announce('THE RIFT TREMBLES… PITLORD HAS AWAKENED!',2100);}
function a04KillPit(team){a04Pit.alive=false;a04Pit.group.visible=false;a04PitRespawn=a04Time(now())+180;a04PitBuff[team]=a04Time(now())+90;announce(team===A04_BLUE?'THE RIFT BOWS TO YOUR WILL.':'THE PITLORD HAS FALLEN TO THE ENEMY.',1900);}
addEventListener('keydown',e=>{if(e.code==='KeyP'&&!e.repeat)a04SpawnPit(true)});

function a04Pos(o){return o.group?o.group.position:o._group.position}
function a04LaneUnlocked(t){if(t.stage===0)return true;return !towers.some(x=>x.userData.team===t.team&&x.userData.lane===t.lane&&x.userData.stage===t.stage-1&&x.userData.alive)}
function a04CoreOpen(team){return !towers.some(x=>x.userData.team===team&&x.userData.stage>=2&&x.userData.alive)}
function a04MinionSupport(pos,defTeam,r=9){return a04Minions.some(m=>m.alive&&m.team!==defTeam&&m.group.position.distanceTo(pos)<=r)}
function a04StructureDamage(s,dmg,team){if(!s.alive)return;if(s.kind==='tower'&&!a04LaneUnlocked(s)){if(team===A04_BLUE)announce('DESTROY THE PREVIOUS TOWER FIRST',650);return}if(s.kind==='core'&&!a04CoreOpen(s.team)){if(team===A04_BLUE)announce('THE CORE IS PROTECTED',700);return}if(!a04MinionSupport(a04Pos(s),s.team,s.kind==='core'?10:9))dmg*=.05;if(team===A04_BLUE&&a04PitBuff.blue>a04Time(now()))dmg*=1.10;s.hp=Math.max(0,s.hp-dmg);fxBurst(a04Pos(s));if(s.hp<=0){s.alive=false;s._group.visible=false;if(s.kind==='tower'){announce(team===A04_BLUE?'THEIR FORTRESS CRUMBLES.':'YOUR FORTRESS FALLS.',1200);if(team===A04_BLUE)player.gold+=260}else{a04Ended=true;announce(s.team===A04_RED?'VICTORY · THE RIFT IS YOURS.':'DEFEAT · YOUR JOURNEY ENDS HERE.',3200)}}}
function a04KillUnit(e,byTeam){e.alive=false;e.group.visible=false;if(e.kind==='minion'){if(byTeam===A04_BLUE)player.gold+=e.type==='special'?75:45}else if(e.kind==='jungle'){e.respawnAt=a04Time(now())+45;if(byTeam===A04_BLUE){player.gold+=e.type==='purple'?180:110;if(e.type==='red')player.redBuffUntil=a04Time(now())+60;if(e.type==='blue')player.blueBuffUntil=a04Time(now())+60;announce(`${e.name} SLAIN`,600)}}else if(e.kind==='pitlord')a04KillPit(byTeam)}
function a04Hurt(e,dmg,byTeam=A04_BLUE){if(!e||!e.alive)return;if(e.kind==='tower'||e.kind==='core')return a04StructureDamage(e,dmg,byTeam);e.hp=Math.max(0,e.hp-dmg);if(e.body?.material){e.body.material.emissive?.setHex?.(0x70152b);e.body.material.emissiveIntensity=1.7;setTimeout(()=>{if(e.body?.material)e.body.material.emissiveIntensity=0},80)}fxBurst(a04Pos(e));if(e.hp<=0)a04KillUnit(e,byTeam)}

const a03Nearest=nearest,a03HurtEnemy=hurtEnemy;
nearest=function(range=Infinity){let best=a03Nearest(range),d0=best?player.group.position.distanceTo(best.group.position):range;const list=[...a04Minions.filter(m=>m.alive&&m.team===A04_RED),...a04Jungle.filter(j=>j.alive)];if(a04Pit.alive)list.push(a04Pit);for(const tw of towers)if(tw.userData.team===A04_RED&&tw.userData.alive)list.push(tw.userData);if(redCore.userData.alive)list.push(redCore.userData);for(const e of list){const d=player.group.position.distanceTo(a04Pos(e));if(d<d0){d0=d;best=e}}return best};
hurtEnemy=function(e,dmg){if(e?.kind)return a04Hurt(e,dmg,A04_BLUE);return a03HurtEnemy(e,dmg)};

attack=function(){const t=now();if(t<cds.attack||!player.alive||a04Ended)return;cds.attack=t+dur.attack;player.attackAnim=1;const e=nearest(player.attackRange);fxSlash(player.group.position,player.facing);if(!e){announce('NO TARGET IN RANGE',430);return}player.facing.copy(a04Pos(e)).sub(player.group.position).setY(0).normalize();let dmg=player.attackDamage*(player.redBuffUntil>a04Time(t)?1.10:1);if(player.deadlineTarget===e&&t<player.deadlineUntil){dmg+=560;announce('DEADLINE',1000);fxRing(a04Pos(e),0xff284c,.8,6,.45);if(e.hp/e.maxHp<.25)dmg=e.hp+1;player.deadlineTarget=null;player.deadlineUntil=0}if(e.kind)a04Hurt(e,dmg,A04_BLUE);else a03HurtEnemy(e,dmg)};
skill1=function(){const t=now();if(t<cds.s1||!player.alive)return;cds.s1=t+dur.s1;player.attackAnim=1;announce('SEVER');fxSlash(player.group.position,player.facing);fxRing(player.group.position,0xd93758,.8,4.8,.38);const list=[...enemies,...a04Minions,...a04Jungle];if(a04Pit.alive)list.push(a04Pit);for(const e of list){if(!e.alive||e.team===A04_BLUE)continue;const off=a04Pos(e).clone().sub(player.group.position).setY(0),d=off.length();if(d<=4.8&&off.normalize().dot(player.facing)>.05)(e.kind?a04Hurt(e,330,A04_BLUE):a03HurtEnemy(e,330))}};
skill3=function(){const t=now();if(t<cds.s3||!player.alive)return;cds.s3=t+dur.s3;announce('EXECUTION STEP');const start=player.group.position.clone();fxAfterimage(start);player.group.position.addScaledVector(player.facing,6.2);player.group.position.x=THREE.MathUtils.clamp(player.group.position.x,-57,57);player.group.position.z=THREE.MathUtils.clamp(player.group.position.z,-57,57);fxRing(player.group.position,0xbf3152,.5,3.2,.28);const e=nearest(2.5);if(e)(e.kind?a04Hurt(e,270,A04_BLUE):a03HurtEnemy(e,270))};
ultimate=function(){const t=now();if(t<cds.ult||!player.alive)return;let e=null,d0=11;for(const x of [...enemies,...a04Minions.filter(m=>m.team===A04_RED),...a04Jungle,...(a04Pit.alive?[a04Pit]:[])]){if(!x.alive)continue;const d=player.group.position.distanceTo(a04Pos(x));if(d<d0){d0=d;e=x}}if(!e){announce('NO TARGET TO MARK');return}cds.ult=t+dur.ult;player.deadlineTarget=e;player.deadlineUntil=t+6;announce('YOUR DEADLINE HAS COME',1400);const mark=new THREE.Mesh(new THREE.TorusGeometry(.75,.09,6,28),new THREE.MeshBasicMaterial({color:0xff3456,transparent:true,opacity:.9}));mark.position.set(0,4.1,0);mark.rotation.x=Math.PI/2;e.group.add(mark);FX.push({m:mark,t:0,dur:6,type:'mark',parent:e.group})};

function a04EnemyMinion(team,pos,range){let b=null,bd=range;for(const m of a04Minions){if(!m.alive||m.team===team)continue;const d=pos.distanceTo(m.group.position);if(d<bd){bd=d;b=m}}return b}
function a04LaneTower(defTeam,lane){return towers.filter(t=>t.userData.team===defTeam&&t.userData.lane===lane&&t.userData.alive).sort((a,b)=>a.userData.stage-b.userData.stage)[0]?.userData||null}
function a04MovePath(m,dt){if(m.index>=m.path.length)return;const dest=m.path[m.index],v=dest.clone().sub(m.group.position).setY(0);if(v.length()<1){m.index++;return}v.normalize();m.group.position.addScaledVector(v,m.speed*dt);m.group.rotation.y=Math.atan2(v.x,v.z)}
function a04Projectile(from,to,color,onHit,dur=.38){const orb=new THREE.Mesh(new THREE.SphereGeometry(.15,7,6),new THREE.MeshBasicMaterial({color}));orb.position.copy(from);scene.add(orb);FX.push({m:orb,t:0,dur,type:'projectile',from:orb.position.clone(),to:to.clone(),onHit})}
function a04UpdateMinions(dt,t){const mt=a04Time(t);for(const m of a04Minions){if(!m.alive)continue;const enemy=a04EnemyMinion(m.team,m.group.position,m.range+.5);const defTeam=m.team===A04_BLUE?A04_RED:A04_BLUE;let s=null;if(!enemy){const tw=a04LaneTower(defTeam,m.lane);if(tw&&m.group.position.distanceTo(a04Pos(tw))<m.range+1.2)s=tw;else{const core=defTeam===A04_RED?redCore.userData:blueCore.userData;if(core.alive&&a04CoreOpen(defTeam)&&m.group.position.distanceTo(a04Pos(core))<m.range+1.4)s=core}}const target=enemy||s;if(target){if(mt>=m.nextHit){m.nextHit=mt+(m.type==='ranged'?1.3:1.05);const dmg=m.damage*(a04PitBuff[m.team]>mt?1.15:1);if(m.type==='ranged')a04Projectile(m.group.position.clone().add(new THREE.Vector3(0,1,0)),a04Pos(target).clone().add(new THREE.Vector3(0,1,0)),m.team===A04_BLUE?0x67b8ff:0xff6577,()=>{if(target.alive)a04Hurt(target,dmg,m.team)});else a04Hurt(target,dmg,m.team)}}else a04MovePath(m,dt)}}
function a04UpdateJungle(dt,t){const mt=a04Time(t);for(const j of a04Jungle){if(!j.alive){if(mt>=j.respawnAt){j.alive=true;j.hp=j.maxHp;j.group.position.copy(j.spawn);j.group.visible=true}continue}const d=j.group.position.distanceTo(player.group.position);if(player.alive&&d<7.2){const v=player.group.position.clone().sub(j.group.position).setY(0);if(d>2){j.group.position.addScaledVector(v.normalize(),j.speed*dt);j.group.rotation.y=Math.atan2(v.x,v.z)}else if(mt>=j.nextHit){j.nextHit=mt+1.3;hurtPlayer(j.damage)}}else{const home=j.spawn.clone().sub(j.group.position).setY(0);if(home.length()>1)j.group.position.addScaledVector(home.normalize(),1.2*dt)}}}
function a04UpdatePit(dt,t){const mt=a04Time(t);if(!a04Pit.alive){if((!a04PitSpawned&&mt>=210)||(a04PitRespawn&&mt>=a04PitRespawn)){a04PitRespawn=0;a04SpawnPit(true)}return}const d=a04Pit.group.position.distanceTo(player.group.position);if(player.alive&&d<8){const v=player.group.position.clone().sub(a04Pit.group.position).setY(0);if(d>2.8)a04Pit.group.position.addScaledVector(v.normalize(),1.0*dt);else if(mt>=a04Pit.nextHit){a04Pit.nextHit=mt+1.45;hurtPlayer(a04Pit.damage)}}}

const a03UpdateEnemies=updateEnemies;
updateEnemies=function(dt,t){a03UpdateEnemies(dt,t);a04UpdateMinions(dt,t);a04UpdateJungle(dt,t);a04UpdatePit(dt,t)};
updateTowers=function(dt,t){const mt=a04Time(t);for(const tw of towers){const s=tw.userData;if(!s.alive)continue;s.crystal.rotation.y+=dt*1.5;let target=null,bd=s.range;for(const m of a04Minions){if(!m.alive||m.team===s.team)continue;const d=tw.position.distanceTo(m.group.position);if(d<bd){bd=d;target=m}}if(!target&&s.team===A04_RED&&player.alive){const d=tw.position.distanceTo(player.group.position);if(d<bd){bd=d;target=player}}if(target&&mt>=s.nextShot){s.nextShot=mt+1;const tp=target===player?player.group.position:target.group.position;a04Projectile(tw.position.clone().add(new THREE.Vector3(0,4.7,0)),tp.clone().add(new THREE.Vector3(0,1.2,0)),s.team===A04_BLUE?0x5bb6ff:0xff4d64,()=>{if(target===player)hurtPlayer(s.damage);else if(target.alive)a04Hurt(target,s.damage,s.team)},.5)}}};

const a03UpdateUi=updateUi;
updateUi=function(t){a03UpdateUi(t);const mt=Math.max(0,a04Time(t)),mi=Math.floor(mt/60),se=Math.floor(mt%60);if(a04Hud.timer)a04Hud.timer.textContent=`${mi}:${String(se).padStart(2,'0')}`;if(a04Hud.gold)a04Hud.gold.textContent=`${Math.floor(player.gold)} GOLD`;if(a04Hud.wave)a04Hud.wave.textContent=`WAVE ${a04Wave}`;if(a04Hud.pit)a04Hud.pit.textContent=a04Pit.alive?'PITLORD: ALIVE':mt<210?`PITLORD: ${Math.ceil(210-mt)}s`:a04PitBuff.blue>mt?'PITLORD: BLUE BUFF':a04PitRespawn?`PITLORD: ${Math.ceil(a04PitRespawn-mt)}s`:'PITLORD: READY';ui.statusText.textContent=player.deadlineTarget&&t<player.deadlineUntil?'DEADLINE ACTIVE':a04PitBuff.blue>mt?'PITLORD SIEGE BUFF':'ALPHA 0.4 MATCH TEST'};
const a03DrawMinimap=drawMinimap;
drawMinimap=function(){a03DrawMinimap();const w=ui.minimap.width,h=ui.minimap.height,P=(x,z)=>[(x+HALF)/WORLD*w,(z+HALF)/WORLD*h],dot=(x,z,c,r)=>{const p=P(x,z);mm.fillStyle=c;mm.beginPath();mm.arc(p[0],p[1],r,0,Math.PI*2);mm.fill()};for(const m of a04Minions)if(m.alive)dot(m.group.position.x,m.group.position.z,m.team===A04_BLUE?'#6bb8ff':'#ff7180',1.25);for(const j of a04Jungle)if(j.alive)dot(j.group.position.x,j.group.position.z,j.type==='purple'?'#ad68e8':j.type==='blue'?'#4da4ff':j.type==='red'?'#ff4b5e':'#d3a14c',1.7);if(a04Pit.alive)dot(a04Pit.group.position.x,a04Pit.group.position.z,'#d482ff',4);for(const tw of towers)if(!tw.userData.alive){const p=P(tw.position.x,tw.position.z);mm.strokeStyle='#555';mm.lineWidth=2;mm.beginPath();mm.moveTo(p[0]-3,p[1]-3);mm.lineTo(p[0]+3,p[1]+3);mm.moveTo(p[0]+3,p[1]-3);mm.lineTo(p[0]-3,p[1]+3);mm.stroke()}};

function updateMatchSystems(dt,t){const mt=a04Time(t);if(!a04Ended&&mt>=a04NextWave){a04SpawnWave();a04NextWave+=20}if(!a04PitSpawned&&mt>=210)a04SpawnPit();}
