import test from 'node:test';
import assert from 'node:assert/strict';
import {createUpgrades,grantLevelPoints,upgradeStatus,spendUpgrade,skillEffects,reduceDamage} from '../progression.mjs';
test('level 1 offers exactly one point and only basic skills',()=>{for(const key of ['s1','s2','s3']){const u=createUpgrades();assert.equal(upgradeStatus(u,1,key).allowed,true);}const u=createUpgrades();assert.equal(upgradeStatus(u,1,'ult').allowed,false);assert.equal(upgradeStatus(u,1,'stats').allowed,false);assert.deepEqual(spendUpgrade(u,1,'s1'),{});assert.equal(u.points,0);assert.equal(spendUpgrade(u,1,'s2'),null);});
test('one grant per level, including skipped levels, capped at 15',()=>{const u=createUpgrades();assert.equal(grantLevelPoints(u,6),5);assert.equal(u.points,6);assert.equal(grantLevelPoints(u,6),0);assert.equal(grantLevelPoints(u,2),0);grantLevelPoints(u,999);assert.equal(u.points,15);});
test('ultimate ranks unlock at 4, 6, 9 and banked points work later',()=>{const u=createUpgrades();grantLevelPoints(u,15);for(const [level,allowed]of [[3,false],[4,true],[5,false],[6,true],[8,false],[9,true],[15,false]]){assert.equal(upgradeStatus(u,level,'ult').allowed,allowed);if(allowed)spendUpgrade(u,level,'ult');}assert.equal(u.ranks.ult,3);const banked=createUpgrades();grantLevelPoints(banked,9);for(let i=0;i<3;i++)assert.notEqual(spendUpgrade(banked,9,'ult'),null);});
test('stat bundle unlocks at 6 and caps at five purchases',()=>{const u=createUpgrades();grantLevelPoints(u,15);assert.equal(spendUpgrade(u,5,'stats'),null);for(let i=0;i<5;i++)assert.deepEqual(spendUpgrade(u,6,'stats'),{health:2,physical:2,magical:2});assert.equal(spendUpgrade(u,15,'stats'),null);assert.equal(u.points,10);});
test('each normal skill has ten ranks; failure never consumes a point',()=>{for(const key of ['s1','s2','s3']){const u=createUpgrades();grantLevelPoints(u,15);for(let i=0;i<10;i++)assert.notEqual(spendUpgrade(u,15,key),null);assert.equal(u.ranks[key],10);assert.equal(spendUpgrade(u,15,key),null);assert.equal(u.points,5);}});
test('ranks strengthen effects; physical/magic mitigation preserves true damage',()=>{const a=skillEffects({s1:1,s2:1,s3:1,ult:1}),b=skillEffects({s1:10,s2:10,s3:10,ult:3});for(const k of Object.keys(a))assert.ok(b[k]>a[k]);assert.equal(skillEffects({}).sever,0);assert.equal(reduceDamage(100,0),100);assert.equal(reduceDamage(100,100),50);assert.equal(reduceDamage(100,100,'true'),100);});
